variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  TZ: Europe/Paris

stages:
  - build

build_package:
  stage: build
  needs: []
  image: debian:buster-slim
  script:
    - apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt-get -y install g++ libboost-tools-dev libboost-test-dev libssl-dev libkrb5-dev libgssglue-dev libsnappy-dev libpng-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libx264-dev libbz2-dev gettext git libhyperscan-dev
    - git submodule update --init
    - mkdir test_tmpdir
    - OPENSSL_NO_DEPRECATED_3_0=1 TMPDIR_TEST=test_tmpdir bjam -j4 linkflags="-static-libstdc++" variant=release -q cxxflags='-DREDEMPTION_DISABLE_NO_BOOST_PREPROCESSOR_WARNING'
  artifacts:
    when: always
    name: "$CI_JOB_NAME"
    paths:
      - bin/gcc-*/release
      - test_tmpdir
    expire_in: 1 day
