variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_REDEMPTION_ANALYZE: redemption-analyze
  IMAGE_SESMAN_TESTS: sshproxies-tests  # image from sshproxies repo
  IMAGE_PAGES: sshproxies-tagger  # image from sshproxies repo
  TESTDIR: test_tmpdir

stages:
  - build-docker-images
  - build

build-analyze-image:
  stage: build-docker-images
  image: docker.io/docker:19.03
  variables:
    BUILD_ANALYZE_PATH: builder/analyze/
  script:
    # DOCKER_AUTH_CONFIG only works when pulling images from private repo for jobs...
    - echo "${WAB_PROXIES_NEXUS_TOKEN}" | docker login -u "${WAB_PROXIES_NEXUS_USER}" "${NEXUS_WAB_PROXIES_URL}" --password-stdin
    - docker build -t ${IMAGE_REDEMPTION_ANALYZE} -f ${BUILD_ANALYZE_PATH}/Dockerfile ${BUILD_ANALYZE_PATH}
    - docker tag ${IMAGE_REDEMPTION_ANALYZE} ${NEXUS_WAB_PROXIES_URL}/${IMAGE_REDEMPTION_ANALYZE}
    - docker push ${NEXUS_WAB_PROXIES_URL}/${IMAGE_REDEMPTION_ANALYZE}
  when: manual

test-sesman:
  stage: build
  image: ${NEXUS_WAB_PROXIES_URL}/${IMAGE_SESMAN_TESTS}
  script:
    - cd tools/sesman/
    - coverage run -m unittest discover -t . tests
    - coverage report
    - coverage xml
  artifacts:
    paths:
      - tools/sesman/coverage.xml
    expire_in: 1 day
  only:
    - merge_requests
    - future


branch-pages:
  stage: build
  image: ${NEXUS_WAB_PROXIES_URL}/${IMAGE_PAGES}
  variables:
    GITLAB_REMOTE: ci
    GIT_BRANCH: pages
  script:
    - mkdir "tmp"
    - tools/compute_doc_percent.sh "tmp"
    - tools/conf_migration_tool/conf_migrate.py --dump=json > tmp/migrate.json
    - cp projects/redemption_configs/autogen/doc/*.json tmp
    - cp projects/redemption_configs/pages/config.html tmp/index.html
    - git config user.email "cipipeline@wallix.com"
    - git config user.name "CI Pipeline"
    - git remote remove "${GITLAB_REMOTE}" || true
    - git remote add "${GITLAB_REMOTE}" "https://${PAGES_ACCESS_NAME}:${PAGES_ACCESS_TOKEN}@gitlab.corp.wallix.com/git/redemption.git"
    - git fetch "${GITLAB_REMOTE}"
    - git switch "${GIT_BRANCH}" || git checkout -b "${GIT_BRANCH}" "${GITLAB_REMOTE}/${GIT_BRANCH}"
    - rm -rf "public/${CI_COMMIT_BRANCH}"
    - mkdir -p "public"
    - mv "tmp" "public/${CI_COMMIT_BRANCH}"
    - git add "public/${CI_COMMIT_BRANCH}"
    - if git commit -m "Update page from ${CI_COMMIT_BRANCH} ${CI_COMMIT_SHORT_SHA}"; then
    -   git push "${GITLAB_REMOTE}" "${GIT_BRANCH}"
    - fi
  only:
    - future
    # - maintenance_bastion_11.0


build-project:
  stage: build
  needs: []
  except:
    - tags
  image: debian:buster-slim
  script:
    - apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install g++ libboost-tools-dev libboost-test-dev libssl-dev libkrb5-dev libgssglue-dev libsnappy-dev libpng-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libx264-dev libbz2-dev gettext git libhyperscan-dev
    - git submodule update --init
    - mkdir -p "$TESTDIR"
    - TMPDIR_TEST="$TESTDIR" bjam -j4 linkflags="-static-libstdc++" variant=release -q cxxflags='-DREDEMPTION_DISABLE_NO_BOOST_PREPROCESSOR_WARNING' && rm -r "$TESTDIR"
  artifacts:
    when: always
    name: "$CI_JOB_NAME"
    paths:
      - bin/gcc-*/release
      - "$TESTDIR"
    exclude:
      - bin/gcc-*/release/*/
      - bin/gcc-*/release/*.o
      - bin/gcc-*/release/libunit_test.so
    expire_in: 1 day


build-analyze:
  stage: build
  needs: []
  except:
    - tags
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: ${NEXUS_WAB_PROXIES_URL}/${IMAGE_REDEMPTION_ANALYZE}
  script:
    - ./tools/gitlab-analyze.sh ${FULL} |& tee report.txt
  artifacts:
    when: always
    paths:
      - report.txt
  timeout: 4h 30m

sonarqube-check:
  stage: build
  needs: [build-project, test-sesman]
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - future
