sudo: false
language: cpp

addons:
  apt:
    packages:
      - g++-4
      - libssl-dev
      - libpng12-dev
      - libboost-dev
      - libsnappy-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - libavcodec-ffmpeg56
      - libavformat-ffmpeg56
      - libavutil-ffmpeg54
      - libswscale-ffmpeg3
    sources: &sources
      - ubuntu-toolchain-r-test


matrix:
  include:
    - os: linux
      env: TOOLSET=gcc-4.9
      compiler: gcc
      before_script:
        - "echo -e 'using gcc : 4.9 : g++-4.9 : <cxxflags>-fdiagnostics-color=always ;' > ~/user-config.jam"

    - os: linux
      env: TOOLSET=clang
      compiler: clang

script:
  #- sudo cp tools/bjam-patch/clang-linux.jam /usr/share/boost-build/tools/clang-linux.jam
  - bjam linkflags=-c --toolset=$TOOLSET $CXXFLAGS -q exe


#branches:
#  only:
#    - master

notifications:
  email:
    recipients:
      - jpoelen@wallix.com
      - rzhou@wallix.com
      - cgrosjean@wallix.com
      - cmoroldo@wallix.com
      #- jinthavong@wallix.com
      #- mtan@wallix.com
    on_success: never
    on_failure: always
