language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CC" = 'gcc' ] ; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y ; fi
  - if [ "$CC" = 'gcc' ] ; then sudo apt-get update -qq ; fi
  - if [ "$CC" = 'gcc' ] ; then "echo -e 'using gcc : 4.8 : g++-4.8 ;

using gcc : 4.9 : /usr/bin/g++-4.9 ;" ; fi

install:
  - sudo apt-get install -qq libssl-dev libpng12-dev libboost-dev libsnappy-dev
  - if [ "$CXX" = 'g++' ] ; sudo apt-get install -qq g++-4.9 g++-4.8 ; fi

script:
  - if [ "$CC" = 'gcc' ] ; then bjam linkflags=-c --toolset=gcc-4.8 -q exe ; fi
  - if [ "$CC" = 'gcc' ] ; then bjam linkflags=-c --toolset=gcc-4.9 -q exe ; fi
  - if [ "$CC" = 'clang' ] ; bjam linkflags=-c --toolset=clang -q exe ; fi

os:
  - linux

#branches:
#  only:
#    - master

notifications:
  email:
    recipients:
      - jpoelen@wallix.com
      - rzhou@wallix.com
      - cgrosjean@wallix.com
    on_success: never
    on_failure: always
